---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.2.0
serverless_language: ''
polling_url: https://atmo.inscog.eu/?station={{station}}&pollutant={{pollutant}}
polling_headers: ''
polling_body: ''
id: 443596
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: pollutant
  field_type: xhrSelect
  name: Polluant
  endpoint: https://atmo.inscog.eu/pollutants.php
  http_verb: GET
  exclude_csrf_token: true
- keyname: station
  field_type: xhrSelect
  name: Station
  depends_on: pollutant
  endpoint: https://atmo.inscog.eu/stations.php?pollutant={{pollutant}}
  http_verb: GET
  exclude_csrf_token: true
name: Atmo Grand Est
description: 24h air quality from Atmo Grand Est
refresh_interval: 60
